# Generated by Django 4.2.8 on 2024-01-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='botines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('talle', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='camiseta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=30)),
                ('talle', models.CharField(max_length=30)),
                ('año', models.IntegerField()),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='short',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=30)),
                ('talle', models.CharField(max_length=30)),
                ('año', models.IntegerField()),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
    ]
