# Generated by Django 4.2.8 on 2024-01-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppeliculas', '0002_futbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='duracion',
            field=models.FloatField(),
        ),
    ]
